### ISSUE TITLE
Could you please update models relevant to SEW_ResNet  codes experimented?

### ISSUE THREAD

**Issue by ChidanandKumarKS** [Gus-Lab/temporal_efficient_training#1]
@Jackn0 
Thanks for your interesting work in this area with better results with smaller observations. 
Could you please update models relevant to SEW_ResNet  codes experimented? Awaiting for your reply

**Comment by Jackn0** [comment]
Hello, you can obtain the SEW-ResNet34 pth model in https://drive.google.com/drive/folders/18o432ckZ_e51bq7AWUYtC7_vf1fasSU4?usp=sharing. We are using LIF model with hard rest instead of IF model in SEW-ResNet34. Thanks for your attention.

**Comment by ChidanandKumarKS** [comment]
@Jackn0 
Kindly give permission to download

**Comment by chowkamlee81** [comment]
Hi,

Do you have python codes pertaining to SEW-ResNet34.pth

**Comment by Jackn0** [comment]
Sorry, I have added permission. And the model code also put into the same path.

**Comment by ChidanandKumarKS** [comment]
@Jackn0 
Thanks helped a lot.
