### ISSUE TITLE
Some problems

### ISSUE THREAD

**Issue by Maybe2022** [Gus-Lab/temporal_efficient_training#3]
A little confused, I saw in another paper that vgg11 achieved 76.2 accuracy on dvs-cifar10; It is only one percentage point less than the 77.33 reported in your paper; TET_ Is the performance improvement range of loss on dvs-cifar10 about 1-2 points?

**Comment by Serbian-strong** [comment]
can't agree more.

**Comment by Serbian-strong** [comment]
can't agree more.
